# Generated by Django 4.2.1 on 2023-06-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.TextField(default='null', max_length=255, unique=True),
        ),
    ]
