# Generated by Django 4.2.1 on 2023-06-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.TextField(default=None, max_length=255, unique=True),
        ),
    ]
